apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
        - name: testapi
          image: tokyj515/docker-kubernetes-test:latest
          ports:
            - containerPort: 8080
