name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          java-package: jdk

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t tokyj515/docker-kubernetes-test .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push tokyj515/docker-kubernetes-test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            docker pull tokyj515/docker-kubernetes-test
            kubectl apply -f docker-kubernetes-test/deploy.yaml
