name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          java-package: jdk

      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t tokyj515/docker-kubernetes-test .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push tokyj515/docker-kubernetes-test

  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Pull Docker image
        run: docker pull tokyj515/docker-kubernetes-test

      - name: Create and start Docker container in detached mode
        run: docker create --name extract-container tokyj515/docker-kubernetes-test

      - name: Copy deploy.yaml from container to EC2 root directory
        run: docker cp extract-container:/app/deploy.yaml /home/ubuntu/deploy.yaml

      - name: Apply Kubernetes deployment
        run: kubectl apply -f /home/ubuntu/deploy.yaml

      - name: Clean up Docker container
        run: docker rm -f extract-container
